### ISSUE TITLE
Alt-shift-D doesn't work for .litcoffee or .coffee.md

### ISSUE THREAD

**Issue by tdsfugal** [SublimeText/CoffeeScript#190]
Alt-shift-d (compile and display) works fine on plain old .coffee files, but doesn't display the transpiled .js for literate coffeescript.  Literate coffee script (.litcoffee and .coffee.md) files seem to compile and run just fine.  Am I doing something wrong?

BTW - excellent plugin.  Alt-shift-D is a fantastic productivity boost. 

(Using better coffee script in Sublime Text 2 on osX 10.9.5.)

**Comment by iainhouston** [comment]
Picking this thread up again: 

      Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
      return self.run(edit, **args)
      File "CoffeeScript in /Users/.../Better CoffeeScript.sublime-package", line 217, in run
      File "CoffeeScript in /Users/.../Better CoffeeScript.sublime-package", line 88, in brew
      File "CoffeeScript in /Users/.../Better CoffeeScript.sublime-package", line 43, in run
      File "CoffeeScript in /Users/.../Better CoffeeScript.sublime-package", line 74, in _run
      File "./subprocess.py", line 824, in __init__
      File "./subprocess.py", line 1448, in _execute_child
      FileNotFoundError: [Errno 2] No such file or directory: 'coffee'  

in simple test project with almost exact same setup as @TDSFugal  except I'm using Sublime Text 3.

![first_litcoffee_ _bettercoffee](https://cloud.githubusercontent.com/assets/537596/7697853/72a2116a-fe03-11e4-8cb8-35706937a364.png)

**Comment by markalfred** [comment]
Hi @iainhouston, do you have coffeescript installed and have its install location set in the `binDir`? If you follow the steps in the [FAQ](https://github.com/aponxi/sublime-better-coffeescript#faq), this may help to diagnose or resolve the issue

**Comment by iainhouston** [comment]
Yes, it was the `binDir` setting. I didn't scroll far enough down the README. Please accept my apologies and my thanks for your patient reply. .

**Comment by markalfred** [comment]
Happy to help, @iainhouston! Happy coding! :beers:
